## 문제1_데이터 전처리
insta.txt 데이터는 corona를 태그로한 약 instagram 게시글을 크롤링한 데이터 입니다. 해당 데이터를 이용하여 인스타그램 태그를 이용한 분석을 하고 싶습니다. 이를 위한 데이터 전처리 함수를 만들고 전처리를 진행하여 주세요.
1. 데이터를 불러온 후, 하나의 문자열로 읽어오세요  
2. 빈칸을 채워주세요
    - 빈칸1 : 해당 텍스트 안에는 게시글이 POST+숫자(ex: POST94)로 구분되어 있습니다. 이를 기준으로 각 게시글을 분리할 수 있도록 빈칸에 정규표현식을 작성하세요
    - 빈칸2 : 추출한 게시글에서 태그만을 추출할 수 있도록 빈칸에 정규표현식을 작성하세요
        - #을 포함하여 추출하세요
        - #뒤의 영숫자 개수가 2개 이상인 것만 추출할 수 있게 작성하세요
        - ex) "\s"
    - 빈칸3: RegexpTokenizer클래스의 tokenize 함수를 이용하여 문장을 구분하세요
        - tokenize 함수 : 텍스트를 인자로 받아서 해당 분류기를 이용하여 텍스트를 분류, 이를 각 리스트 원소로 한 리스트 반환
        - ex) RegxpTokenizer(정규표현식).tokenize(text)
    - 빈칸4: RegexpTokenizer클래스의 tokenize를 이용하여 각 문장에서 단어를 추출하세요.
    - 빈칸5 : words 리스트 안의 각 단어에서 "#"을 제거한 후 모두 소문자로 변경하고 개별 단어가 스톱워드의 단어에 포함되지 않으면 filtered_words 리스트에 추가하세요.
    - 빈칸6 : 해당 리스트 안에서의 중복된 단어를 제거하세요.  
1. 함수를 실행하세요

In [1]:
import nltk
nltk.download("stopwords") # 언어별 스톱 워드를 제공
stopwords = nltk.corpus.stopwords.words("english")

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\yurik\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.


In [56]:
f = open("insta.txt", 'r')
data = f.readline()
f.close()

In [82]:
# 인스타그램 게시글에서 태그만을 추출하는 함수
def tags_extraction(data):
    import re # 정규표현식 모듈
    from nltk.tokenize import RegexpTokenizer # 정규표현식을 사용할 수 있는 토큰화함수
    
    words = [] # 단어 토큰을 저장할 list
    filtered_words = [] # 필터화된 단어 토큰을 저장할 list
    
    """
    RegexpTokenizer(정규표현식, gaps=False)
    gaps=True이면 해당 정규표현식을 기준으로 분류
    gaps=False이면 해당 정규표현식에 해당되는 것들을 추출
    """
    tokenizer_sentence = RegexpTokenizer("POST\d+", gaps=True) # 문장 토큰 분류기 생성
    tokenizer_word=RegexpTokenizer("#[a-zA-Z0-9]{2,}") # 단어 토큰 분류기 생성
    
    words=tokenizer_sentence.tokenize(data)
    words = [tokenizer_word.tokenize(i) for i in words]
      
    words = [item for items in words for item in items]
    words = [e[1:].lower() for e in words]

    for word in words:
        if word not in stopwords: 
            filtered_words.append(word) 
    filtered_words
    
    filtered_words = sorted(set(filtered_words), key=lambda x:filtered_words.index(x))
    return filtered_words

In [83]:
result=tags_extraction(data) # 불러온 데이터를 인자로 넣어서 실행하세요

In [84]:
result

['style',
 'nature',
 'happy',
 'dance',
 'funny',
 'dirumahaja',
 'insta',
 'photooftheday',
 'comment',
 'fashion',
 'likeforlikeback',
 'youtube',
 'meme',
 'followme',
 'malaysia',
 'jakarta',
 'viralpost',
 'dagelan',
 'corona',
 'girl',
 'beautiful',
 'viralindonesia',
 'bhfyp',
 'following',
 'likeforfollow',
 'foryou',
 'quotes',
 'thirdeyethoughts',
 'thirdeyethirst',
 'positivevibes',
 'innerwork',
 'enlightenment',
 'innerwisdom',
 'lightworker',
 'loveyourself',
 'powerofpositivtiy',
 'spiritualawakening',
 'spiritual',
 'higherawakening',
 'cosmicconsciousness',
 'divinity',
 'intuition',
 'spirit',
 'trust',
 'love',
 'usa',
 'thirdeyeawakening',
 'awakening',
 'inspirational',
 'motivationalquotes',
 'spirituality',
 'stayhome',
 'staysafe',
 'life',
 'sunday',
 'instagood',
 'musermedan',
 'tiktoksea',
 'likeeappindonesia',
 'musergenerationindo',
 'musically',
 'muserid',
 'tiktokhits',
 'musergeneration',
 'muserindo',
 'musicallyindonesia',
 'tiktok',
 'tiktokindo',


# 문제2_CountVectorizer
- disney_plus_shows.csv 데이터는 디즈니+스트림 서비스에서 이용할 수 있는 쇼에 대한 정보입니다. 데이터를 사용하여 밑의 문제를 풀어주세요 !

In [2]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer

- 데이터의 모든 결측치를 제거하여 주세요.(행 기준)

In [4]:
# 데이터 불러오기
d_show = pd.read_csv('disney_plus_shows.csv', index_col=0)[:5]

In [13]:
# 결측치 제거
d_show=d_show.dropna(axis=0)

- CountVectorizer() 메소드를 이용하여 count_vec 객체를 만들어주세요.
- 파리미터 옵션
    + stop_words="english"
    + analyzer='word', 
    + ngram_range=(1, 2)
    + min_df=1
    + max_features=None
- 생성된 객체에 d_show데이터의 'plot' 변수를 넣어주세요.

In [14]:
# 객체 생성
count_vec=CountVectorizer(stop_words="english",analyzer="word",ngram_range=(1,2),min_df=1,max_features=None)
# plot 변수 fitting
final=count_vec.fit_transform(d_show['plot'])

- get_feature_names()를 사용해 데이터의 단어들을 출력해 주세요.
- vocabulary_를 사용해 단어들이 각각 몇번씩 쓰였는지 출력해주세요.

In [16]:
vocab=count_vec.get_feature_names()
print(vocab)
count_vec.vocabulary_

['coat', 'coat instead', 'creates', 'creates extravagant', 'cruella', 'cruella devil', 'dalmatian', 'dalmatian puppies', 'date', 'date ill', 'designer', 'designer plots', 'devil', 'devil gets', 'does', 'evil', 'evil high', 'extravagant', 'extravagant fur', 'extravagant mess', 'fashion', 'fashion designer', 'fur', 'fur coat', 'gets', 'gets prison', 'goes', 'goes puppies', 'high', 'high fashion', 'ill', 'ill tempered', 'instead', 'instead creates', 'make', 'make extravagant', 'mess', 'older', 'older sister', 'order', 'order make', 'plots', 'plots steal', 'popular', 'popular teenager', 'pretty', 'pretty popular', 'prison', 'prison goes', 'puppies', 'puppies order', 'sister', 'sister does', 'steal', 'steal dalmatian', 'teenager', 'teenager date', 'tempered', 'tempered older']


{'pretty': 45,
 'popular': 43,
 'teenager': 55,
 'date': 8,
 'ill': 30,
 'tempered': 57,
 'older': 37,
 'sister': 51,
 'does': 14,
 'pretty popular': 46,
 'popular teenager': 44,
 'teenager date': 56,
 'date ill': 9,
 'ill tempered': 31,
 'tempered older': 58,
 'older sister': 38,
 'sister does': 52,
 'evil': 15,
 'high': 28,
 'fashion': 20,
 'designer': 10,
 'plots': 41,
 'steal': 53,
 'dalmatian': 6,
 'puppies': 49,
 'order': 39,
 'make': 34,
 'extravagant': 17,
 'fur': 22,
 'coat': 0,
 'instead': 32,
 'creates': 2,
 'mess': 36,
 'evil high': 16,
 'high fashion': 29,
 'fashion designer': 21,
 'designer plots': 11,
 'plots steal': 42,
 'steal dalmatian': 54,
 'dalmatian puppies': 7,
 'puppies order': 50,
 'order make': 40,
 'make extravagant': 35,
 'extravagant fur': 18,
 'fur coat': 23,
 'coat instead': 1,
 'instead creates': 33,
 'creates extravagant': 3,
 'extravagant mess': 19,
 'cruella': 4,
 'devil': 12,
 'gets': 24,
 'prison': 47,
 'goes': 26,
 'cruella devil': 5,
 'devil gets'

# 문제3 COO, CSR 적용

In [17]:
from scipy import sparse

In [18]:
matrix_array = np.array([[0,2,3,0,1,4],
                  [3,5,9,0,0,8],
                  [4,3,0,1,2,8],
                  [2,0,9,9,1,0],
                  [0,0,2,0,9,1],
                  [8,2,0,3,0,0]])

- 0이 아닌 데이터 추출
- 행 위치와 열 위치를 각각 array로 생성
- 행 위치 배열의 고유한 값의 시작 위치 인덱스를 배열로 생성

In [20]:
# 0이 아닌 데이터 추출
data=np.array([2,3,1,4,3,5,9,8,4,3,1,2,8,2,9,9,1,2,9,1,8,2,3])
# 행 위치
row_pos=np.array([0,0,0,0,1,1,1,1,2,2,2,2,2,3,3,3,3,4,4,4,5,5,5])
# 열 위치
col_pos=np.array([1,2,4,5,0,1,2,5,0,1,3,4,5,0,2,3,4,2,4,5,0,1,3])
# 고유한 인덱스 배열
row_pos_ind=[0,4,8,13,17,20]

- COO 형식으로 변환
- CSR 형식으로 변환
- toarray()를 통해 출력 확인

In [22]:
# COO 형식으로 변환
sparse_coo=sparse.coo_matrix((data,(row_pos,col_pos))).toarray()
print(sparse_coo)
# CSR 형식으로 변환
sparse_csr=sparse.csr_matrix((data,col_pos,row_pos_ind)).toarray()
print(sparse_csr)

[[0 2 3 0 1 4]
 [3 5 9 0 0 8]
 [4 3 0 1 2 8]
 [2 0 9 9 1 0]
 [0 0 2 0 9 1]
 [8 2 0 3 0 0]]
[[0 2 3 0 1 4]
 [3 5 9 0 0 8]
 [4 3 0 1 2 8]
 [2 0 9 9 1 0]
 [0 0 2 0 9 1]]
